#
# Copyright 2022 GoPro Inc.
#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

from pynopegl_utils.misc import SceneCfg

import pynopegl as ngl


def compare(cfg: SceneCfg, scene0: ngl.Node, scene1: ngl.Node, xsplit: float) -> ngl.Node:
    """
    Compare two scenes by splitting them vertically. The scene generated by
    this function relies on the stencil buffer, and thus can not work properly
    if one of the compared scenes uses it.
    """

    # Fill the stencil buffer with 1's on the left side, and 0's on the right
    scene_mask = ngl.RenderColor()
    scene_mask = ngl.Scale(scene_mask, factors=(xsplit, 1, 1), anchor=(-1, 0, 0))
    scene_mask = ngl.GraphicConfig(
        scene_mask,
        color_write_mask="",  # no need to write the color themselves, only the stencil
        stencil_test=True,
        stencil_ref=1,
        stencil_read_mask=0,
        stencil_write_mask=0xFF,
        stencil_fail="replace",
        stencil_depth_fail="replace",
        stencil_depth_pass="replace",
    )

    # Draw the 1st scene where the stencil is equal to 1 (left)
    scene0 = ngl.GraphicConfig(scene0, stencil_func="equal")

    # Draw the 2nd scene where the stencil is not equal to 1 (right)
    scene1 = ngl.GraphicConfig(scene1, stencil_func="notequal")

    stencil_test = ngl.GraphicConfig(
        ngl.Group(children=(scene0, scene1)),
        stencil_test=True,
        stencil_ref=1,
        stencil_read_mask=0xFF,
        stencil_write_mask=0,
        stencil_fail="keep",
        stencil_depth_fail="keep",
        stencil_depth_pass="keep",
    )

    return ngl.Group(children=(scene_mask, stencil_test))
