#!/bin/sh

set -eu

if [ ! -f CHANGELOG.md ]; then
    echo "This script must be executed from the project root directory" >&2
    exit 1
fi

if ! git diff-index --quiet HEAD; then
    echo "Git index is not clean" >&2
    exit 1
fi

today=$(date -I)

# If the year changed since last release, we reset the digit to 0, otherwise we
# simply increment it
cur_year=$(date '+%Y')
prv_prj_year=$(cut -f1 -d. VERSION)
if [ "$prv_prj_year" -ne "$cur_year" ]; then
    new_digit=0
else
    prv_prj_digit=$(cut -f2 -d. VERSION)
    new_digit=$((prv_prj_digit+1))
fi

# Project version bump
prv_prj_ver=$(cat VERSION)
new_prj_ver="${cur_year}.${new_digit}"
echo "New project version: $prv_prj_ver → $new_prj_ver"

# libnodegl version bump
cur_lib_ver=$(cat libnodegl/VERSION)
printf "Enter new libnodegl version [current: %s]: " "$cur_lib_ver"
read -r new_lib_ver

# Execute the version bump: we are verbose with set -x to be transparent about
# the actions that matters
set -x
echo "$new_prj_ver" > VERSION
echo "$new_lib_ver" > libnodegl/VERSION
sed "/^## \[Unreleased\]/a \\\n## [$new_prj_ver] [libnodegl $new_lib_ver] - $today" -i CHANGELOG.md
git add CHANGELOG.md VERSION libnodegl/VERSION
git commit -m "Release $new_prj_ver"
git tag "v${new_prj_ver}"
