# Warning: this name must stay in sync with the badges referenced in the README
name: 'build iOS 🍏'

on:
  push:
    branches:
      - 'main'
  pull_request:
  schedule:
      - cron: "0 0 * * 6"  # Run every Saturday at midnight

jobs:
  ios-build:

    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [aarch64]

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew install meson nasm jq pkg-config

    - name: Build
      run: |
        ./configure.py --buildtype debug --debug-opts gl vk --host iOS --host-arch ${{ matrix.arch }}
        make -f Makefile.iOS.${{ matrix.arch }}
