name: Linters

on:
  pull_request:
    branches:
      - main

jobs:

  isort:
    name: isort
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: isort/isort-action@master
        with:
          configuration: "--check --diff"

  black:
    name: black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable
        with:
          options: "--check --diff"
