name: 'build macOS release'

on:
  workflow_run:
    workflows: ["create GitHub release"]
    types: [completed]

jobs:
  macos:

    permissions:
      contents: write
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - tool: nope-viewer
            tool_fullname: NopeViewer
          - tool: nope-diff
            tool_fullname: NopeDiff

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew install ffmpeg freetype fribidi harfbuzz python@3.11 curl pkg-config nasm create-dmg

    - name: Setup venv
      run: |
        $(brew --prefix)/opt/python@3.11/libexec/bin/python configure.py

    - name: Build
      run: |
        make

    - name: Build installer
      run: |
        . venv/bin/ngli-activate
        pip install pyinstaller
        libarchive=$(brew list libarchive | grep libarchive.[0-9]*.dylib)
        pyinstaller \
            --collect-all pynopegl_utils \
            --add-binary "$(which ffmpeg):bin" \
            --add-binary "$(which ffprobe):bin" \
            --add-binary "$libarchive:." \
            --windowed \
            -i scripts/pyinstaller/${{ matrix.tool }}.icns \
            scripts/pyinstaller/${{ matrix.tool }}.py
        create-dmg ${{ matrix.tool }}.dmg dist/${{ matrix.tool }}.app

    - name: Upload DMG
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        output_file="${{ matrix.tool_fullname }}-$(cat VERSION)-x86_64.dmg"
        mv ${{ matrix.tool }}.dmg $output_file
        gh release upload v$(cat VERSION) $output_file
