name: 'build Linux release'

on:
  workflow_run:
    workflows: ["create GitHub release"]
    types: [completed]

jobs:
  linux:

    permissions:
      contents: write
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt -y update
        #
        # python3-venv is required to prevent the following issue:
        #     The virtual environment was not created successfully because ensurepip is not
        #     available.  On Debian/Ubuntu systems, you need to install the python3-venv
        #     package using the following command.
        #
        #         apt-get install python3-venv
        #
        sudo apt -y install libsdl2-dev libva-dev python3-venv spirv-tools glslang-dev libvulkan-dev mesa-vulkan-drivers vulkan-validationlayers
        sudo apt -y install ffmpeg libavcodec-dev libavutil-dev libavformat-dev libavdevice-dev libavfilter-dev libswscale-dev libswresample-dev libpostproc-dev
        sudo apt -y install libfreetype-dev libharfbuzz-dev libfribidi-dev
        sudo apt -y install fuse

    - name: Build
      run: |
        scripts/appimage/build.sh

    - name: Upload AppImage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload v$(cat VERSION) appimage/NopeViewer-x86_64.AppImage
